### ISSUE TITLE
Redux store not passed through context into cell renderers via React in v13.0

### ISSUE THREAD

**Issue by tardis10** [ag-grid/ag-grid-react#88] opened 2017-08-29 13:43 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In version 13.0, when requesting access to the Redux store through React's context property, the cell renderer gets a null state instance.  This is passed via the top-level Redux provider and is accessible at the grid level, but not in any cells and is seemingly blocked by the grid itself.

```
class Renderer extends React.Component {
    static contextTypes = {
        store: PropTypes.object,
    };
    ...
}
```

**Expected behavior**
It is expected to be able to access the store via context.  Version 12.0.2 does not have this issue and works as expected.

**Minimal reproduction of the problem with instructions**
Creation of a React renderer framework with context request as above.  this.context.state will produce a null value, which prevents using Redux dispatches.

**What is the motivation / use case for changing the behavior?**
Restoring previous functionality.  This change broke several grid apps on our internal site.

**Please tell us about your environment:**
Ubuntu 16.04 using latest React/Redux and ag-grid 13.0.0.  Rolling back to ag-grid 12.0.2 fixes the issue.

* **ag-grid-react version:** 2.0.X
13.0.0 (no newer releases noted via ncu)

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
13.0.0 (no newer releases noted via ncu)

* **React version:** 2.0.X
15.6.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 60

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by makinggoodsoftware** [comment] 2017-08-30 09:13
Sorry for the trouble,

Based on this example 

https://www.ag-grid.com/example-react-redux/?framework=all#gsc.tab=0

It seems to be working OK in our end.

Would you be able to provide us with a zip/plunkr/github so that we can reproduce the error?

Thanks

**Comment by guybensh** [comment] 2017-08-30 13:26
Hi,

I'm also experiencing the same issue as @tardis10.
All context types/providers you providing to your application is not passed to AgGridReact.
That means that:
1. All connected components are missing the store you provided through the Provider Component.
2. All the material-ui components are missing the muiTheme you provided through the MuiThemeProvider component.


Since the example working in your end @makinggoodsoftware ,
Try to add a material-ui/connected component to cellRendereFramework and you'll recieve the error.


Thanks.

**Comment by SmoooZ** [comment] 2017-08-30 14:16
Hi,
we are having the same problem when using react-router <Link>s : react-router is using the React Context to transfer routing information but the cell renderers do get a null instance, therefore our links are not working properly with ag-grid v13 or v13.0.1.
It works fine with v12 however.
Can be easily tested with a structure like
<Router>
   <AgGridReact>
      <CustomCellRenderer>
         <Link>

Is this problem related to AG-665 ? (supposed to be CLOSED in v13) 
We hold an enterprise license.

Thank you !

**Comment by tardis10** [comment] 2017-08-30 14:16
Agree with @guybensh above.  The problem should be easily created by using cellRendererFramework with a React component (as my code snippet above), then attempting to access the store via the context (this.context.store) in the render() function for the class.  In 13.0.0 this is undefined, and in 12.0.2 this is the correct store object.  This does not seem to be an issue with React/Redux itself as simply downgrading ag-grid without changing React/Redux solves the problem.

Not sure this helps but https://github.com/ag-grid/ag-grid-react/issues/18 seems to be a potentially similar issue that was fixed a while back.

**Comment by seanlandsman** [comment] 2017-08-31 14:45
@SmoooZ - AG-665 is related to VueJS, not React - just fyi

We're looking at this issue atm

**Comment by seanlandsman** [comment] 2017-08-31 16:25
I've created an example that reproduces this problem

@makinggoodsoftware and I are looking at this issue as a priority

**Comment by seanlandsman** [comment] 2017-09-05 06:06
Hi - this issue should now be resolved in 13.1.0

thanks

**Closed by seanlandsman** 2017-09-05 06:06 UTC

**Comment by tardis10** [comment] 2017-09-05 15:38
Confirm this appears resolved.  Thanks!

**Comment by Q-Man** [comment] 2019-04-12 03:32
I have the same problem with the version 20.x of AG-Grid. When I use a Redux-connected component inside the render function of a CellRenderer I get the following error:

Uncaught Invariant Violation: Could not find "store" in the context of "Connect(MyComponentName)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(MyComponentName) in connect options.

I'm using:
- ag-grid-community: 20.2.0
- ag-grid-react: 20.2.0
- react: 16.8.6
- react-dom: 16.8.6
- react-redux: 7.0.1
- redux: 4.0.1
