### ISSUE TITLE
doesn't support new React (16.3) Context API

### ISSUE THREAD

**Issue by urrri** [ag-grid/ag-grid-react#131] opened 2018-08-15 13:29 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Context consumer doesn't receive context in a cell renderer if context provider declared above the grid.
Because `unstable_rendersubtreeintocontainer` doesn't work with new Context API

**Expected behavior**
new Context API should work.
There is Portal API (`ReactDOM.createPortal`), which supports all new APIs and replaces deprecated `unstable_rendersubtreeintocontainer`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-react version:** 18.1.X

* **ag-Grid/ag-Grid-Enterprise version:** 18.1.X

* **React version:** 16.4.X

* **Browser:** [Chrome 68 ]

* **Language:** [ ES6/7 | ES5]

**Comment by urrri** [comment] 2018-08-15 14:29
https://codesandbox.io/s/kw4pro8k27 - sample, how golden-layout managed exactly the same problem with very similar behavior

**Comment by ashrafhadden** [comment] 2018-08-22 06:57
I can confirm this, I have the same environment as @urrri and I also wasn't able to get Context API consumers to pass in their value. My `cellRenderers` would only receive the Provider's `defaultValue` which happens when 

> The defaultValue argument is only used by a Consumer when it does not have a matching Provider above it in the tree.

_Source: https://reactjs.org/docs/context.html#reactcreatecontext_

This is probably because the `cellRendererFramework` and `frameworkComponents` are rendered to the React root div in the Virtual DOM as referenced in my Issue #132 Meaning they have nothing above them, no parents.

**Comment by seanlandsman** [comment] 2018-12-18 14:00
Hi

This will be fixed in our next release - currently scheduled for mid Jan 2019.

thanks

**Closed by seanlandsman** 2018-12-18 14:00 UTC

**Comment by mellis481** [comment] 2019-01-28 16:09
@seanlandsman Has this been released?

**Comment by lilbumblebear** [comment] 2019-02-08 15:17
Similar to #142, which appears to be solved using the updated documentation found here:
https://www.ag-grid.com/react-more-details/#react-portals
